name: user_messaging_platform
description: >-
  A plugin which provides a Dart API for the User Messaging Platform (UMP) SDK, which is the
  Consent Management Platform (CMP) SDK provided as part of Google's Funding Choices.
version: 0.1.0+1
repository: https://github.com/blaugold/user_messaging_platform
issue_tracker: https://github.com/blaugold/user_messaging_platform/issues

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.2

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: UserMessagingPlatformPlugin
      android:
        package: com.terwesten.gabriel.user_messaging_platform
        pluginClass: UserMessagingPlatformPlugin
